import type { DashboardHighlight, DashboardOverview } from "@gtm-os/types";
import type { ReactNode } from "react";
import { FindJobsButton } from "./find-jobs-button";
import { QuickLaunchPanel } from "./quick-launch-panel";

type DashboardShellProps = { highlights: DashboardHighlight[]; overview: DashboardOverview };
const icons = { grid: "⌘", spark: "✦", briefcase: "▣", radar: "◉", arrow: "↗" };

function SectionLabel({ children }: { children: ReactNode }) { return <p className="section-label">{children}</p>; }

function StatCard({ label, value, detail, tone }: { label: string; value: number; detail: string; tone: string }) {
  return <article className={`stat-card ${tone}`}><div className="stat-card-top"><span className="stat-dot" /><span className="stat-label">{label}</span><span className="stat-arrow">{icons.arrow}</span></div><p className="stat-value">{value}</p><p className="stat-detail">{detail}</p></article>;
}

export function DashboardShell({ highlights, overview }: DashboardShellProps) {
  const { summary, recentApplications, pipelineStages, nextActions, careerPlan } = overview;
  const discoveredJobs = overview.discoveredJobs ?? [];
  const resumeVersions = overview.resumeVersions ?? [];

  return <main className="app-shell">
    <aside className="sidebar">
      <div className="brand"><span className="brand-mark">J</span><span>job ops <em>os</em></span></div>
      <div className="workspace-switcher"><span className="avatar avatar-coral">P</span><span><small>Workspace</small><strong>Pratham&apos;s HQ</strong></span><span className="chevron">⌄</span></div>
      <nav className="side-nav" aria-label="Primary navigation">
        <span className="nav-group-label">Workspace</span>
        <a className="nav-item active" href="#overview"><span>{icons.grid}</span>Overview</a>
        <a className="nav-item" href="#pipeline"><span>{icons.briefcase}</span>Applications <b>{summary.totalApplications}</b></a>
        <a className="nav-item" href="#matches"><span>{icons.spark}</span>Role matches</a>
        <a className="nav-item" href="#companies"><span>{icons.radar}</span>Companies</a>
        <span className="nav-group-label nav-group-spaced">Automations</span>
        <a className="nav-item" href="#launch"><span>✧</span>Application agent <i className="live-pill">Live</i></a>
        <a className="nav-item" href="#activity"><span>◷</span>Activity log</a>
      </nav>
      <div className="sidebar-bottom"><div className="credits"><span className="pulse-dot" /><span><strong>Ready for your keys</strong><small>Manual actions enabled</small></span></div><a className="nav-item" href="#settings"><span>⚙</span>Settings</a><div className="profile-row"><span className="avatar avatar-dark">P</span><span><strong>Pratham</strong><small>Personal workspace</small></span><span className="more">•••</span></div></div>
    </aside>

    <div className="content-wrap">
      <header className="topbar"><div className="breadcrumb"><span>Workspace</span><b>/</b><strong>Overview</strong></div><div className="top-actions"><a className="icon-button" aria-label="Search role matches" href="#matches">⌕</a><a className="icon-button notification" aria-label="View activity" href="#activity">♢<i /></a><a className="top-avatar" aria-label="Open settings" href="#settings">P</a></div></header>
      <div className="dashboard-content" id="overview">
        <section className="hero-section reveal"><div><div className="eyebrow"><span className="eyebrow-dot" />Your private job command center</div><h1>Your job search,<br /><span>in motion.</span></h1><p className="hero-copy">Paste one job description, generate a truthful tailored resume, and keep every opportunity moving forward.</p></div><FindJobsButton /></section>

        <section className="stats-grid reveal reveal-delay-1"><StatCard label="Applications" value={summary.totalApplications} detail="Tracked end to end" tone="tone-coral" /><StatCard label="Replies" value={summary.replies} detail={summary.totalApplications ? `${Math.round((summary.replies / summary.totalApplications) * 100)}% response rate` : "No responses yet"} tone="tone-lavender" /><StatCard label="Interviewing" value={summary.interviewing} detail="Active conversations" tone="tone-blue" /><StatCard label="Offers" value={summary.offers} detail="Offer-track progress" tone="tone-green" /></section>

        <section className="main-grid reveal reveal-delay-2" id="pipeline"><article className="panel pipeline-panel"><div className="panel-heading"><div><SectionLabel>Pipeline health</SectionLabel><h2>Application momentum</h2></div><a className="ghost-button" href="#activity">View activity ↗</a></div><div className="pipeline-chart"><div className="chart-lines"><span /><span /><span /><span /></div><div className="chart-bars">{pipelineStages.map((stage, index) => <div className="chart-column" key={stage.label}><div className={`bar bar-${index}`} style={{ height: `${Math.max(stage.percentage, stage.count ? 8 : 3) * 2.1}%` }}><b>{stage.count}</b></div><span>{stage.label}</span></div>)}</div></div><div className="pipeline-footer"><span><i className="legend-dot coral" />Live data from your workspace</span><strong>{discoveredJobs.length} <span>fresh matches</span></strong></div></article><article className="panel queue-panel"><div className="panel-heading"><div><SectionLabel>Up next</SectionLabel><h2>Priority queue</h2></div><a className="text-link" href="#launch">View all {icons.arrow}</a></div><div className="task-list">{nextActions.map((task, index) => <a className="task-row" href={index === 0 ? "#launch" : "#activity"} key={task.title}><span className={`task-check ${index === 0 ? "task-active" : ""}`}>{index === 0 ? "→" : ""}</span><div><strong>{task.title}</strong><p>{task.description}</p></div><span className={`priority priority-${task.priority}`}>{task.priority}</span></a>)}</div></article></section>

        <section className="split-grid reveal" id="roles"><article className="panel role-panel"><div className="panel-heading"><div><SectionLabel>AI role matches</SectionLabel><h2>Where you fit best</h2></div><span className="ai-badge">{icons.spark} AI ranked</span></div><p className="panel-description">Based on your experience, strengths, and the kind of work you want to do next.</p><div className="role-list">{careerPlan.roleSuggestions.slice(0, 3).map((role, index) => <div className="role-row" key={role.title}><span className="role-rank">0{index + 1}</span><div className="role-main"><strong>{role.title}</strong><span>{role.summary}</span><div className="tag-row">{role.searchQueries.slice(0, 2).map((query) => <small key={query}>{query}</small>)}</div></div><div className="fit-score"><strong>{role.fitScore}%</strong><span>fit</span></div></div>)}</div><a className="bottom-link" href="#launch">Tailor a resume for a role {icons.arrow}</a></article><article className="panel company-panel" id="companies"><div className="panel-heading"><div><SectionLabel>Target companies</SectionLabel><h2>Good signals, right now</h2></div><span className="signal-badge"><i /> Profile</span></div><p className="panel-description">Company targets from your career plan. Live enrichment becomes available after adding provider keys.</p><div className="company-list">{careerPlan.companyMatches.slice(0, 3).map((company) => <div className="company-row" key={company.id}><span className="company-logo">{company.name.slice(0, 1)}</span><div><strong>{company.name}</strong><span>{company.targetRole}</span></div><span className="company-score">{company.fitScore}%</span></div>)}</div><a className="bottom-link" href="#settings">Configure enrichment {icons.arrow}</a></article></section>

        <section className="jobs-section panel reveal" id="matches"><div className="panel-heading"><div><SectionLabel>Fresh job matches</SectionLabel><h2>{discoveredJobs.length ? `${discoveredJobs.length} opportunities ready` : "Find your first live matches"}</h2></div><a className="text-link" href="#overview">Back to top {icons.arrow}</a></div><p className="panel-description">Jobs from your connected, permitted sources appear here. Use the hero button to refresh them.</p>{discoveredJobs.length ? <div className="job-match-list">{discoveredJobs.slice(0, 6).map((job) => <article className="job-match-row" key={job.id}><div className="job-match-main"><span className="job-source">{job.source}</span><h3>{job.title}</h3><p>{job.company} · {job.location ?? "Location not specified"}</p><small>{job.reasons[0] ?? "Ranked against your profile"}</small></div><div className="job-match-score"><strong>{job.fitScore}%</strong><span>fit</span>{job.url ? <a href={job.url} target="_blank" rel="noreferrer">View post ↗</a> : null}</div></article>)}</div> : <div className="empty-panel"><span className="empty-panel-icon">⌁</span><strong>No live job matches yet</strong><p>Connect a permitted source in Vercel, then use “Find jobs now”. Results will be saved here and in Supabase.</p><a className="small-action-link" href="#settings">Open setup checklist ↗</a></div>}</section>

        <section className="launch-wrap reveal" id="launch"><div className="launch-heading"><div><SectionLabel>Application agent</SectionLabel><h2>Turn a job post into momentum.</h2><p>Paste the complete JD and let the agent tailor your resume, draft outreach, and keep your pipeline current.</p></div><span className="agent-orb">✦</span></div><QuickLaunchPanel /></section>

        <section className="panel activity-panel reveal" id="activity"><div className="panel-heading"><div><SectionLabel>Recent activity</SectionLabel><h2>Everything in one place</h2></div><a className="text-link" href="#launch">Create application {icons.arrow}</a></div><div className="table-wrap">{recentApplications.length ? <table><thead><tr><th>Company</th><th>Role</th><th>Status</th><th>Next step</th></tr></thead><tbody>{recentApplications.map((application) => <tr key={application.id}><td><span className="table-company"><i>{application.companyName.slice(0, 1)}</i><strong>{application.companyName}</strong></span></td><td>{application.jobTitle}</td><td><span className={`status status-${application.status}`}>{application.status.replaceAll("_", " ")}</span></td><td>{application.nextStep ?? "Review next action"}</td></tr>)}</tbody></table> : <div className="empty-panel"><strong>Your application activity will appear here.</strong><p>Generate a resume from a JD to create the first saved application.</p><a className="small-action-link" href="#launch">Start with a JD ↗</a></div>}</div></section>

        <section className="resume-library panel reveal" id="resumes"><div className="panel-heading"><div><SectionLabel>Resume library</SectionLabel><h2>Saved tailored versions</h2></div><a className="text-link" href="#launch">Create another {icons.arrow}</a></div>{resumeVersions.length ? <div className="resume-version-list">{resumeVersions.map((version) => <div className="resume-version-row" key={version.id}><span className="resume-file">▤</span><div><strong>{version.profileName}</strong><span>Updated {version.updatedAt ? new Date(version.updatedAt).toLocaleDateString() : "just now"}</span></div><a href="#activity">View application ↗</a></div>)}</div> : <div className="empty-library">Your generated resumes will be versioned here after the first JD is processed.</div>}</section>

        <section className="settings-panel panel reveal" id="settings"><div className="panel-heading"><div><SectionLabel>Workspace settings</SectionLabel><h2>Connect your keys once</h2></div><span className="settings-lock">Private</span></div><p className="panel-description">The product workflow is ready. Only provider credentials and permitted job-source identifiers belong in Vercel Environment Variables; secrets never ship to the browser.</p><div className="settings-grid"><div><strong>AI provider</strong><span>AI_API_KEY · AI_BASE_URL · AI_MODEL</span></div><div><strong>Database</strong><span>SUPABASE_URL · SUPABASE_SERVICE_ROLE_KEY</span></div><div><strong>Job sources</strong><span>Greenhouse, Lever, Ashby, or Adzuna</span></div></div><a className="settings-action" href="https://vercel.com/dashboard" target="_blank" rel="noreferrer">Open Vercel environment variables ↗</a></section>

        <section className="insight-grid reveal">{highlights.map((highlight) => <article className="insight-card" key={highlight.title}><span className="insight-icon">✦</span><SectionLabel>{highlight.eyebrow}</SectionLabel><h3>{highlight.title}</h3><p>{highlight.description}</p></article>)}</section>
      </div>
    </div>
  </main>;
}
